### ISSUE TITLE
Move Primary Source into a gadget

### ISSUE THREAD

**Issue by Tpt** [google/primarysources#23]
We should move Primary Source frontend into a gadget on Wikidata in order to make it more easy to use.

The drawback is that gadget are in the Mediawiki: namespace and, so, require admin rights to be modified.

**Comment by Tpt** [comment]
@tomayac I am ready to create this gadget as soon as I get your green light

**Comment by tomayac** [comment]
I have some pending changes to make before, in order to make the user
script testable. These are (partly) covered in
https://phabricator.wikimedia.org/T95290,
https://phabricator.wikimedia.org/T95289, and
https://phabricator.wikimedia.org/T97247. What would be required to create
the gadget and what is the upgrade strategy?

**Comment by Tpt** [comment]
To create the gadget you have to move the JS and CSS code in the Mediawiki: namespace with the prefix "Gadget-". So in our case the JS file would be in a page like "MediaWiki:Gadget-primarySource.js". And then you just have to edit https://www.wikidata.org/wiki/MediaWiki:Gadgets-definition to register your gadget. for more information see https://en.wikipedia.org/wiki/Wikipedia:Gadget

The drawback is that these two operations requires edit right on the MediaWiki namespace, right which is restricted to admins and some other user groups.

**Comment by mineo** [comment]
Is this fixed, now that https://www.wikidata.org/wiki/Wikidata:Primary_sources_tool only mentions the gadget?

**Comment by Tpt** [comment]
Yes :-)
