### ISSUE TITLE
Allow to filter statements by dataset and upload

### ISSUE THREAD

**Issue by Tpt** [google/primarysources#28]
It would be very nice to be able to filter statements by "datataset" and "upload":

The "dataset" is a set of statement (usually distinguished by source) like "Freebase" or "X and Y research project".
The "upload" is the id of the upload process in order to be able to rollback it.
An "upload" would add data to one "dataset" but a "dataset" may be uploaded in more than one "upload"

## Use cases
- Cancel the upload of a dataset if too many bad data have been imported
- Allows to output statistics for only one dataset
- Allows the user to display only statements from one dataset

### Data structure
- "dataset" is a string like "freebase" that identifies the dataset
- "upload" is a unique identifier which is assigned by the backend during the upload process and then returned to the user. We could use the timestamp of the upload beginning as id.

### Backend
In the database two field are added to the 'statement' table, 'dataset' and 'upload' which contain the "dataset" and the "upload" ids.

Change the /import action to be able to specify a dataset and make it choose and return an upload id.

Edit the /delete action to allow to remove the statements from a specific upload.

Add to /entities/<QID>, /entities/any and /statements/any action a dataset parameter to filter by dataset.

### Frontend
Add somewhere a selector to only display one specific dataset.

@tomayac @wastl What do you think about it?

**Comment by wastl** [comment]
So far, we didn't consider it too important. But if there is a good use case, we should implement it. However, rather than using char columns that consume a lot of space, I would create a separate table "datasets" like

CREATE TABLE dataset (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name VARCHAR(32)
)

and add to the statement table only a column with a foreign key reference to the dataset table. Upload could simply remain an integer ID. I thought about timestamps, but they are more expensive.

There's a problem with cleaning up "bad" data and this is that a statement stores much of its data in the snak, source and qualifier tables. When deleting statements, it would also be necessary to clean up snaks that are no longer referenced, and this is a very expensive operation (kind of a NOT IN). If we really want this feature, I'll try coming up with a usable way. Perhaps we would need to delete statements individually, though.

**Comment by lydiapintscher** [comment]
We're getting a lot of interest for using this for a number of other datasets as the way to get them into Wikidata properly. Being able to tell the data apart seems important.

**Comment by wastl** [comment]
Implemented, rolling it out. When importing statements, it is now necessary to add a &dataset=<string> argument to the REST call, or a -d <STRING> to the inject command line tool.

**Comment by wastl** [comment]
FYI(tomyac): when returning the envelope JSON format, the JSON now also contains for each statement the dataset identifier and the upload ID. Use it in any way you want in the UI ;-)

**Comment by lydiapintscher** [comment]
Thank you! :)
