### ISSUE TITLE
Run backend tests using a continuous integration service

### ISSUE THREAD

**Issue by Tpt** [google/primarysources#29]
We should maybe use a continuous integration service like [Travis](http://docs.travis-ci.com/user/languages/cpp/) to run the backend tests on each commit and pull request.

I can't do it myself as I don't have admin rights on this repo

**Comment by wastl** [comment]
I'd like to avoid over engineering, so as long as there are not too many commits and committers I am not sure if this is really necessary. Particularly since the tests I have are just unit tests and not really integration tests (except the persistence tests, which at least set up an in-memory database). 

For the frontend part I think we don't have any tests so far. Would be good to add some.

**Comment by wastl** [comment]
It's now live: https://travis-ci.org/google/primarysources
