### ISSUE TITLE
Make it possible to not use a dataset via the gadget

### ISSUE THREAD

**Issue by mineo** [google/primarysources#37]
At the moment, most of the "Random Primary Source item"s only suggest adding a Freebase identifier. I'm sorry, but I really can't see the point of me spending time adding identifiers to an already-declared-dead product and would much prefer adding other data, but I can't because I can only choose between "All sources" and "freebase" in the settings. The freebase identifiers that are suggested all seem to be from the "Samsung Freebase-Wikidata mapping" which I would like to disable.

**Comment by Tpt** [comment]
Yes, currently there are a lot of Freebase ids because I have not uploaded yet any other data from Freebase. I hope it'll be done early next week. Then there will still be Freebase ids but I hope that with each 2 or 3 more interesting statements will be provided.

But we should maybe move the Freebase ids outside of the main Freebase dataset or create a feature that allow users to filter a find of statements.

**Comment by wastl** [comment]
Tpt: please tell me when you are ready, I guess we should deploy a new version of the backend as well with the dataset selection feature enabled ...

**Comment by Tpt** [comment]
@wastl I've already deployed yesterday the last version of the backend with a simple git pull/make/make install as suggested by the command line history. Denny gave me access to the Wikimedia Tools Labs project.

**Comment by wastl** [comment]
Ok, there's a "webservice restart" to do as well, but I guess you figured that out ;-)

**Comment by Tpt** [comment]
I have removed the Freebase ids from Primary Sources backend. Adding them was a bad idea.
