### ISSUE TITLE
Backend performance issues

### ISSUE THREAD

**Issue by Tpt** [google/primarysources#43]
The sqlite database is currently very slow after the importation of 8M of new statements. We should maybe consider to keep optimizing the queries or to move to an other SQL backend.

**Comment by Tpt** [comment]
Wikimedia Tools labs provides a MariaDB database server called tools-db: https://wikitech.wikimedia.org/wiki/Help:Tool_Labs/Database#Creating_new_databases

We should maybe consider to use that

**Comment by wastl** [comment]
There are several aspects to this:
- sqlite itself is not slow, but since it is running on an NFS file on the wikitools server the performance is still severly impacted (comparison: on my Laptop it is at least 10 times faster)
- sqlite has a more simplistic locking model, that's why sometimes there are internal server errors; maybe we should not immediately give an internal server error in this case and instead simply wait and retry, or send a temporary failure to the client
- switching to a different database backend should be simple, but I never tried it; if you have the time, please feel free to try; note that using PostgreSQL might be a bit more complicated because it has a different (more standards compliant) way of generating IDs, but MariaDB/MySQL should behave like sqlite

**Comment by Tpt** [comment]
I have switched the database backend to MySQL.

DB informations:
host: tools-db
name: s52462_ps
user and password: see ~/replica.my.cnf file

Simple command to connect: mysql --defaults-file="${HOME}"/replica.my.cnf -h tools-db s52462_ps

**Comment by wastl** [comment]
Looking at error.log it seems to have solved the performance issue, so it was indeed the NFS latency. I'd still like to see some automatic testing for MySQL, maybe I can do something next week.
