### ISSUE TITLE
Can not approve/reject references anymore

### ISSUE THREAD

**Issue by smalyshev** [google/primarysources#74]
Currently, while using Primary Sources gadget, I can no longer approve or reject references since no approve/reject links are presented in the UI. The links for claims are there, but not for references on claims.

**Comment by tfmorris** [comment]
I'm seeing the same thing. Accepting the claim leaves the references highlighted in blue with now Accept/Reject buttons.

**Comment by tomayac** [comment]
This was already tracked in https://github.com/google/primarysources/issues/70. As I wrote there, this is due to a CSS change on the Wikidata side.

CC: @lydiapintscher @brightbyte @JeroenDeDauw Please ping one of your CSS designers to https://github.com/google/primarysources/issues/70. Thanks, and sorry for the blind outreach, I don't know who takes care of Wikidata's CSS.

**Comment by lydiapintscher** [comment]
Poked the right person.
