### ISSUE TITLE
Reference URLs get suggested multiple times

### ISSUE THREAD

**Issue by mineo** [google/primarysources#8]
https://www.wikidata.org/wiki/Q6490983 currently suggests

* http://icanwritefunny.blogspot.com/2013/05/the-electronic-arts-building.html
* http://www.gettyimages.com/detail/news-photo/larry-probst-chairman-of-electronic-arts-inc-walks-with-news-photo/173236074

It doesn't look like that's a bug in the userscript because `curl https://tools.wmflabs.org/wikidata-primary-sources/entities/Q6490983 | sort | uniq -c` already says they're suggested twice.

**Comment by tomayac** [comment]
This should be fixed with https://github.com/google/primarysources/commit/a6091d8df2e790bfa55b6a1dc42bd715803f023d. Thanks for reporting.

**Comment by mineo** [comment]
Thanks for the quick fix! I wonder, though, with the way https://github.com/google/primarysources/blob/master/backend/Persistence.cc#L337-L343 (which seems to be the backend of the "/any" endpoint) won't this eventually lead to "/any" redirecting to a wikidata entity that has an unapproved statement that won't be shown because its approved duplicate is already there?

**Comment by tomayac** [comment]
We are actually in the middle of improving this. @wastl has introduced
two new states, "duplicate" and "blacklisted" yesterday. Whenever we
encounter either duplicate facts or blacklisted sources, we will
automatically set their state accordingly and never suggest them. This
should go live in the next couple of days in the front-end.

**Comment by wastl** [comment]
I was considering doing a duplicate check on import in the backend (had it actually already implemented), but it turned out to dramatically decrease import performance (which was kind of obvious from the beginning, the question is how many statements are going to be imported and how important is performance for this...). This could probably be improved a bit by additional index structures in the database, but it will remain a performance problem. Experience shows that database transactions with alternating INSERT and SELECT queries are starting to trash I/O.

It would be better to clean up the data before importing it if possible (since the transformation is done by a script this should not be too hard). We could also run a periodic background duplicate check and simply mark found statements as duplicate.

You are right about the /any endpoint, of course. The question is how much impact this problem will really have.

**Comment by tomayac** [comment]
FWIW, the deduplification is already implemented in the front-end at
essentially no cost as we get very few new facts per qid:
https://github.com/google/primarysources/blob/ae939b5a19b36b5ef69c8ec449e1a9d261beaa2b/frontend/freebase2wikidata.js#L448-L459.

**Comment by wastl** [comment]
This is now also fixed in the backend. At the end of import, it is now possible to sweep once through the database and mark all duplicates with state "duplicate". In this way we avoid the problem with random returning unapproved duplicate statements.

**Comment by mineo** [comment]
Great, that looks like a thought out solution :-)
